<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Panier extends \App\Entity\Panier implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Formedeboxe' => [parent::class, 'Formedeboxe', null],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'panierqte' => [parent::class, 'panierqte', null],
        "\0".parent::class."\0".'prixunite' => [parent::class, 'prixunite', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        'Formedeboxe' => [parent::class, 'Formedeboxe', null],
        'commandes' => [parent::class, 'commandes', null],
        'id' => [parent::class, 'id', null],
        'panierqte' => [parent::class, 'panierqte', null],
        'prixunite' => [parent::class, 'prixunite', null],
        'total' => [parent::class, 'total', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
