<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxOEE7v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxOEE7v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxOEE7v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxOEE7v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxOEE7v\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxOEE7v',
    'container.build_id' => 'aa9b271d',
    'container.build_time' => 1709565214,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxOEE7v');
